# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import video_pb2 as video__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in video_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideoServiceStub(object):
    """Video Service - handles video operations between services
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVideo = channel.unary_unary(
                '/video.VideoService/GetVideo',
                request_serializer=video__pb2.VideoRequest.SerializeToString,
                response_deserializer=video__pb2.VideoResponse.FromString,
                _registered_method=True)
        self.UpdateVideoStatus = channel.unary_unary(
                '/video.VideoService/UpdateVideoStatus',
                request_serializer=video__pb2.UpdateStatusRequest.SerializeToString,
                response_deserializer=video__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetVideoChunks = channel.unary_stream(
                '/video.VideoService/GetVideoChunks',
                request_serializer=video__pb2.ChunkRequest.SerializeToString,
                response_deserializer=video__pb2.VideoChunk.FromString,
                _registered_method=True)
        self.ReportTranscodeProgress = channel.unary_unary(
                '/video.VideoService/ReportTranscodeProgress',
                request_serializer=video__pb2.TranscodeProgressRequest.SerializeToString,
                response_deserializer=video__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetQueueStatus = channel.unary_unary(
                '/video.VideoService/GetQueueStatus',
                request_serializer=video__pb2.QueueStatusRequest.SerializeToString,
                response_deserializer=video__pb2.QueueStatusResponse.FromString,
                _registered_method=True)
        self.ListVideos = channel.unary_unary(
                '/video.VideoService/ListVideos',
                request_serializer=video__pb2.ListVideosRequest.SerializeToString,
                response_deserializer=video__pb2.ListVideosResponse.FromString,
                _registered_method=True)
        self.SearchVideos = channel.unary_unary(
                '/video.VideoService/SearchVideos',
                request_serializer=video__pb2.SearchVideosRequest.SerializeToString,
                response_deserializer=video__pb2.ListVideosResponse.FromString,
                _registered_method=True)
        self.GetVideoStats = channel.unary_unary(
                '/video.VideoService/GetVideoStats',
                request_serializer=video__pb2.VideoRequest.SerializeToString,
                response_deserializer=video__pb2.VideoStatsResponse.FromString,
                _registered_method=True)
        self.BatchUpdateStatus = channel.unary_unary(
                '/video.VideoService/BatchUpdateStatus',
                request_serializer=video__pb2.BatchUpdateStatusRequest.SerializeToString,
                response_deserializer=video__pb2.BatchStatusResponse.FromString,
                _registered_method=True)


class VideoServiceServicer(object):
    """Video Service - handles video operations between services
    """

    def GetVideo(self, request, context):
        """Get video information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVideoStatus(self, request, context):
        """Update video status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVideoChunks(self, request, context):
        """Get video file chunks for streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTranscodeProgress(self, request, context):
        """Report transcoding progress
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueueStatus(self, request, context):
        """Get transcoding queue status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVideos(self, request, context):
        """List videos with pagination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchVideos(self, request, context):
        """Search videos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVideoStats(self, request, context):
        """Get video statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchUpdateStatus(self, request, context):
        """Batch update video status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideo,
                    request_deserializer=video__pb2.VideoRequest.FromString,
                    response_serializer=video__pb2.VideoResponse.SerializeToString,
            ),
            'UpdateVideoStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVideoStatus,
                    request_deserializer=video__pb2.UpdateStatusRequest.FromString,
                    response_serializer=video__pb2.StatusResponse.SerializeToString,
            ),
            'GetVideoChunks': grpc.unary_stream_rpc_method_handler(
                    servicer.GetVideoChunks,
                    request_deserializer=video__pb2.ChunkRequest.FromString,
                    response_serializer=video__pb2.VideoChunk.SerializeToString,
            ),
            'ReportTranscodeProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTranscodeProgress,
                    request_deserializer=video__pb2.TranscodeProgressRequest.FromString,
                    response_serializer=video__pb2.StatusResponse.SerializeToString,
            ),
            'GetQueueStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueStatus,
                    request_deserializer=video__pb2.QueueStatusRequest.FromString,
                    response_serializer=video__pb2.QueueStatusResponse.SerializeToString,
            ),
            'ListVideos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVideos,
                    request_deserializer=video__pb2.ListVideosRequest.FromString,
                    response_serializer=video__pb2.ListVideosResponse.SerializeToString,
            ),
            'SearchVideos': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchVideos,
                    request_deserializer=video__pb2.SearchVideosRequest.FromString,
                    response_serializer=video__pb2.ListVideosResponse.SerializeToString,
            ),
            'GetVideoStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideoStats,
                    request_deserializer=video__pb2.VideoRequest.FromString,
                    response_serializer=video__pb2.VideoStatsResponse.SerializeToString,
            ),
            'BatchUpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchUpdateStatus,
                    request_deserializer=video__pb2.BatchUpdateStatusRequest.FromString,
                    response_serializer=video__pb2.BatchStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video.VideoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('video.VideoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoService(object):
    """Video Service - handles video operations between services
    """

    @staticmethod
    def GetVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video.VideoService/GetVideo',
            video__pb2.VideoRequest.SerializeToString,
            video__pb2.VideoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVideoStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video.VideoService/UpdateVideoStatus',
            video__pb2.UpdateStatusRequest.SerializeToString,
            video__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVideoChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/video.VideoService/GetVideoChunks',
            video__pb2.ChunkRequest.SerializeToString,
            video__pb2.VideoChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTranscodeProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video.VideoService/ReportTranscodeProgress',
            video__pb2.TranscodeProgressRequest.SerializeToString,
            video__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueueStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video.VideoService/GetQueueStatus',
            video__pb2.QueueStatusRequest.SerializeToString,
            video__pb2.QueueStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVideos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video.VideoService/ListVideos',
            video__pb2.ListVideosRequest.SerializeToString,
            video__pb2.ListVideosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchVideos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video.VideoService/SearchVideos',
            video__pb2.SearchVideosRequest.SerializeToString,
            video__pb2.ListVideosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVideoStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video.VideoService/GetVideoStats',
            video__pb2.VideoRequest.SerializeToString,
            video__pb2.VideoStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchUpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video.VideoService/BatchUpdateStatus',
            video__pb2.BatchUpdateStatusRequest.SerializeToString,
            video__pb2.BatchStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
